### ISSUE TITLE
添加/back返回死亡点

### ISSUE THREAD

**Issue by fanlepian1** [WarSkyGod/TPA#2]
添加/back返回死亡点
我Fork了你的项目，然后添加了这个功能，你可以参考一下我写的代码，学习了你的代码格式，感谢
https://github.com/fanlepian1/TPA/tree/1.3

**Comment by fanlepian1** [comment]
不过还是有点问题的，我写的这个/back需要tpa.back的权限，普通玩家没有，大的问题倒是没有

**Comment by WarSkyGod** [comment]
> 添加/back返回死亡点 我Fork了你的项目，然后添加了这个功能，你可以参考一下我写的代码，学习了你的代码格式，感谢 https://github.com/fanlepian1/TPA/tree/1.3

已更新，非常感谢您的代码，不过下次建议您使用PR提交
