### ISSUE TITLE
我写的back有个非常严重低级的错误

### ISSUE THREAD

**Issue by fanlepian1** [WarSkyGod/TPA#3]
查看Event下面的lastloction这个变量会发现，这个变量是服务器的变量，并不是单独的坐标，所以这就有可能导致玩家在使用back时，传送到其他人的死亡地点

**Comment by WarSkyGod** [comment]
> 查看Event下面的lastloction这个变量会发现，这个变量是服务器的变量，并不是单独的坐标，所以这就有可能导致玩家在使用back时，传送到其他人的死亡地点

感谢提醒，已修复
