### ISSUE TITLE
Could not call method 'public static org.bukkit.Location org.bukkit.Location.d eserialize(java.util.Map)' of class org.bukkit.Location for deserialization

### ISSUE THREAD

**Issue by Apleax** [WarSkyGod/TPA#4]
![image](https://github.com/user-attachments/assets/a18a661c-8614-4e0c-b7b7-d2a5abfb3a92)
在使用/setwarp记录传送点后启动服务器会在控制台抛出此异常,但是实际并不影响使用,我不知道这个错误会不会带来什么后果

**Comment by WarSkyGod** [comment]
> ![image](https://private-user-images.githubusercontent.com/171245879/395646924-a18a661c-8614-4e0c-b7b7-d2a5abfb3a92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxODQyODEsIm5iZiI6MTczNDE4Mzk4MSwicGF0aCI6Ii8xNzEyNDU4NzkvMzk1NjQ2OTI0LWExOGE2NjFjLTg2MTQtNGUwYy1iN2I3LWQyYTVhYmZiM2E5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxMzQ2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmJlMTUwMjI1MGY2ZDhmMmQ4NWJmYjU5NzA3ZTkyZTQ2Y2Y2MmM3ZGFhY2NkMWZjODY2M2QzMmYzNzk3MzIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s1Y7vSqM7yBjg3BsjVvse1z8w4OEu6ov66CCFPKwxyo) 在使用/setwarp记录传送点后启动服务器会在控制台抛出此异常,但是实际并不影响使用,我不知道这个错误会不会带来什么后果

感谢您的issues，这个问题之前有但是因为没导致什么后果所以我无视了，今天我重新看了一下，是因为在世界加载之前调用warp.yml里的Location导致的问题，倒不会导致什么大问题，我把调用Location放在加载完世界之后就没有问题了
