### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "text" is null

### ISSUE THREAD

**Issue by Apleax** [WarSkyGod/TPA#6]
> [03:40:52 ERROR]: Error executing task on Server
> java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "text" is null
>         at com.mojang.brigadier.suggestion.SuggestionsBuilder.suggest(SuggestionsBuilder.java:59) ~[brigadier-1.2.9.jar:?]
>         at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigSuggestionProvider.getSuggestions(BukkitCommandNode.java:141) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.2.9.jar:1.21-130-b1b5d4c]
>         at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:551) ~[paper-1.21.jar:?]
>         at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:531) ~[paper-1.21.jar:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.sendServerSuggestions(ServerGamePacketListenerImpl.java:836) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions0$2(ServerGamePacketListenerImpl.java:797) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
>         at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**_在1.21版本paper中首次使用插件会输出null_**
![image](https://github.com/user-attachments/assets/70d9e843-e0e6-477e-b307-1efc5fc5b98f)

**_并且触发TabCompleter时会抛出NullPointerException_**
![image](https://github.com/user-attachments/assets/f5a45b1b-5976-45f6-aa8a-4a93d76b5aa2)

**_任何向玩家发送的消息都会变成null_**
![image](https://github.com/user-attachments/assets/c8d08d81-7346-4183-bf4d-755310534a34)

以上问题仅仅在第一次加载插件出现,重启服务器就会正常,如果不重启就会一直存在,/tpa reload也没有用

**Comment by Apleax** [comment]
但是功能似乎都不受影响,能正常使用

**Comment by WarSkyGod** [comment]
> > [03:40:52 ERROR]: Error executing task on Server
> > java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "text" is null
> > at com.mojang.brigadier.suggestion.SuggestionsBuilder.suggest(SuggestionsBuilder.java:59) ~[brigadier-1.2.9.jar:?]
> > at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigSuggestionProvider.getSuggestions(BukkitCommandNode.java:141) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.2.9.jar:1.21-130-b1b5d4c]
> > at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:551) ~[paper-1.21.jar:?]
> > at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:531) ~[paper-1.21.jar:?]
> > at net.minecraft.server.network.ServerGamePacketListenerImpl.sendServerSuggestions(ServerGamePacketListenerImpl.java:836) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions0$2(ServerGamePacketListenerImpl.java:797) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
> > at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
> 
> **_在1.21版本paper中首次使用插件会输出null_** ![image](https://private-user-images.githubusercontent.com/171245879/395814083-70d9e843-e0e6-477e-b307-1efc5fc5b98f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMzM4NjMsIm5iZiI6MTczNDIzMzU2MywicGF0aCI6Ii8xNzEyNDU4NzkvMzk1ODE0MDgzLTcwZDllODQzLWUwZTYtNDc3ZS1iMzA3LTFlZmM1ZmM1Yjk4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQwMzMyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWFmMzM2Yjc0MTMxMzhlYTkwZWRmNjgxM2M4NWVlM2U5MmFhMjIyZGYxZWVhZjYzZmExZDAyMGExNjE0MjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aFq5D0V_xhyGBVq2Wxh6mX_bgLrooIBoeebACSrHnAY)
> 
> **_并且触发TabCompleter时会抛出NullPointerException_** ![image](https://private-user-images.githubusercontent.com/171245879/395814449-f5a45b1b-5976-45f6-aa8a-4a93d76b5aa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMzM4NjMsIm5iZiI6MTczNDIzMzU2MywicGF0aCI6Ii8xNzEyNDU4NzkvMzk1ODE0NDQ5LWY1YTQ1YjFiLTU5NzYtNDVmNi1hYThhLTRhOTNkNzZiNWFhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQwMzMyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzcxMDkzNTU1NWM3OTg5YzcyYzUwODk4NjQ1ZmE1OGZjZTRhMzNkZGQ4OTc3MjVmMzdkYWZmN2JjMzg2YWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZaWu8Bn1GgT8V-FQOB3K1mBCXfUJCNQT_sAhiw77x9s)
> 
> **_任何向玩家发送的消息都会变成null_** ![image](https://private-user-images.githubusercontent.com/171245879/395814529-c8d08d81-7346-4183-bf4d-755310534a34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMzM4NjMsIm5iZiI6MTczNDIzMzU2MywicGF0aCI6Ii8xNzEyNDU4NzkvMzk1ODE0NTI5LWM4ZDA4ZDgxLTczNDYtNDE4My1iZjRkLTc1NTMxMDUzNGEzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQwMzMyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTIxODI2MDhlMjQ2YmNiNzY2ZGM1ZGRlYzE4YTI3ZTE2NjBmOTgzMWI3M2Q4NjNlMDFiZDZlYjUyYWE2YTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.a0vxtwrWczF186mP91BVl4-CZax73-rG1HpoD_ME9Qk)
> 
> 以上问题仅仅在第一次加载插件出现,重启服务器就会正常,如果不重启就会一直存在,/tpa reload也没有用

这个问题是因为我昨天修#4的时候疏忽了，把加载语言文件一起放到命令加载之后了:(，完了正巧我测试的时候没有删TPA文件夹测试过，非常感谢
